export const projectsData = [
  {
    id: 1,
    title: "Chatbot for ideation and brainstorming",
    description: "This website helps to generate ideas and mindmaps",
    details: "IdeazBot is a sophisticated AI-driven chatbot designed to elevate brainstorming sessions. It integrates large language models to provide creative suggestions, structure thoughts into mindmaps, and help users overcome writer's block. Built with React and interactive visualization libraries.",
    image: "/images/projects/1.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/Angela112515/ideazBot.git",
    previewUrl: "/projects/1",
    technologies: ["React", "flask", "Grok API", "Tailwind CSS"],
  },
  {
    id: 2,
    title: "Library manager",
    description: "This website helps to reserve books.",
    details: "A comprehensive digital library management system. Users can browse collections, check real-time availability, and reserve books online. It includes an administrative dashboard for managing inventory, tracking loans, and handling user reservations seamlessly.",
    image: "/images/projects/2.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/Angela112515/Biblioflex.git",
    previewUrl: "/projects/2",
    technologies: ["Next.js", "Node.js", "Tailwind CSS", "Lucide React"],
  },
  {
    id: 3,
    title: "Management of a hybrid air conditioning system",
    description: "This site helps to manage a hybrid air conditioning system.",
    details: "An IoT-focused dashboard designed to monitor and optimize hybrid air conditioning systems. It provides real-time data visualization of energy consumption, temperature controls, and system health. The platform enables remote configuration and intelligent scheduling for maximum efficiency.",
    image: "/images/projects/3.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/Angela112515/AirConditionner.git",
    previewUrl: "/projects/3",
    technologies: ["React", "Express.js", "Socket.io"],
  },
  {
    id: 4,
    title: "Data management web application",
    description: "This website helps to manage data of a NGO.",
    details: "A data management platform developed for the Patro St Charles Lwanga to centralize information on children enrolled in the center and its staff. The system enables efficient data collection and secure storage, while providing statistical tools to monitor and analyze the evolution of the number of children over time.",
    image: "/images/projects/4.png",
    tag: ["All", "Mobile"],
    gitUrl: "https://github.com/Angela112515/PatroBaseDeDonneeFinal.git",
    previewUrl: "/projects/4",
    technologies: ["React Native", "express.js", "supabase"],
  },
  {
    id: 5,
    title: "Coca Cola Plateform",
    description: "Digitalization and predictive maintenance of industrial equipment at Coca-Cola",
    details: "An industrial-grade platform developed for Coca-Cola to digitize maintenance workflows. It utilizes predictive analytics and real-time monitoring of industrial equipment to minimize downtime. The dashboard provides maintenance teams with alerts, health scores, and historical data logs for optimized operations.",
    image: "/images/projects/image5.jpeg",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/Angela112515/Cola-track.git/",
    previewUrl: "/projects/5",
    technologies: ["Next.js", "FastAPI", "Python", "PostgreSQL"],
  }
];
